name: Mod CI
on: [push, pull_request]
jobs:
  save-create:
    runs-on: self-hosted
    if: github.event_name == 'push'
      || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v5
      - name: Run save-create
        run: bash tests/run.sh save-create

  world:
    runs-on: self-hosted
    if: github.event_name == 'push'
      || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        # Every file in tests/worlds needs an entry here
        world: [lib, generator, solver]
    steps:
      - uses: actions/checkout@v5
      - name: Run ${{ matrix.world }}
        run: bash tests/run.sh world ${{ matrix.world }}
